[dev]
source      = jmap+oauthbearer://dev%40ronshavit.com@api.fastmail.com:443/.well-known/jmap
outgoing    = jmap://dev%40ronshavit.com@
source-cred-cmd = pass show fastmail.com/me@ronshavit.com/aerc | head -1
outgoing-cred-cmd = pass show fastmail.com/me@ronshavit.com/aerc | head -1
carddav-source = https://dev%40ronshavit.com@carddav.fastmail.com/dav/addressbooks/user/dev@ronshavit.com/Default
carddav-source-cred-cmd = pass show fastmail.com/me@ronshavit.com/carddav-query | head -1
address-book-cmd = carddav-query -S dev %s
default     = Inbox
from        = Ron Shavit <dev@ronshavit.com>
use-labels  = true
cache-state = true
cache-blobs = true
folders-sort = Inbox
