"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [2, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "none"
show_hidden = true
show_symlink = true
scrolloff = 5
title_format = "Yazi: {cwd}"
