include=~/.config/foot/themes/nor.ini
include=~/.config/foot/current_theme.ini

[main]
# font
font=Berkeley Mono:size=14:fontfeatures=-calt:fontfeatures=-liga:fontfeatures=-dlig:fontfeatures=ss02

[cursor]
blink=no

[mouse]
hide-when-typing=yes

[bell]
system=no

[colors-dark]
alpha=0.9
# blur=true

[colors-light]
alpha=0.9
# blur=true

# [key-bindings]
# spawn-terminal=none
# show-urls-launch=none
# prompt-next=none
