[dev]
source      = jmap+oauthbearer://dev%40ronshavit.com@api.fastmail.com:443/.well-known/jmap
outgoing    = jmap://dev%40ronshavit.com@
source-cred-cmd = pass show fastmail.com/me@ronshavit.com/aerc
outgoing-cred-cmd = pass show fastmail.com/me@ronshavit.com/aerc
default     = INBOX
from        = Ron Shavit <dev@ronshavit.com>
use-labels  = true
cache-state = true
cache-blobs = false
