theme = "Default"
default_source = "Nyaa"
download_client = "rqbit"
timeout = 30
scroll_padding = 3
cursor_padding = 4
save_config_on_change = true
hot_reload_config = true

[client]
output_folder = "~/downloads"

[client.rqbit]
base_url = "http://localhost:3030"
use_magnet = true
overwrite = false

[source]
