set -gx wallpaper '{wallpaper}'

set -gx background '{background}'
set -gx foreground '{foreground}'
set -gx cursor '{cursor}'
set -gx border '{color7}'

set -gx color0 '{color0}'
set -gx color1 '{color1}'
set -gx color2 '{color2}'
set -gx color3 '{color3}'
set -gx color4 '{color4}'
set -gx color5 '{color5}'
set -gx color6 '{color6}'
set -gx color7 '{color7}'
set -gx color8 '{color8}'
set -gx color9 '{color9}'
set -gx color10 '{color10}'
set -gx color11 '{color11}'
set -gx color12 '{color12}'
set -gx color13 '{color13}'
set -gx color14 '{color14}'
set -gx color15 '{color15}'

set -gx fish_color_autosuggestion {color8.strip}
set -gx fish_color_cancel {color1.strip} --reverse
set -gx fish_color_command {color10.strip}
set -gx fish_color_comment {color8.strip}
set -gx fish_color_cwd {color2.strip}
set -gx fish_color_cwd_root {color1.strip}
set -gx fish_color_end {color3.strip}
set -gx fish_color_error {color2.strip}
set -gx fish_color_escape {color5.strip}
set -gx fish_color_history_current --bold
set -gx fish_color_host {color12.strip}
set -gx fish_color_host_remote {color12.strip}
set -gx fish_color_keyword {color5.strip}
set -gx fish_color_match --background={color4.strip}
set -gx fish_color_normal {foreground.strip}
set -gx fish_color_operator {color6.strip}
set -gx fish_color_option {color3.strip}
set -gx fish_color_param {color12.strip}
set -gx fish_color_quote {color11.strip}
set -gx fish_color_redirection {color5.strip}
set -gx fish_color_search_match --background={color8.strip}
set -gx fish_color_selection --background={color8.strip}
set -gx fish_color_status {color1.strip}
set -gx fish_color_user {color10.strip}
set -gx fish_color_valid_path --underline

set -gx fish_pager_color_background {background.strip}
set -gx fish_pager_color_completion {foreground.strip}
set -gx fish_pager_color_description {color8.strip}
set -gx fish_pager_color_prefix {color10.strip}
set -gx fish_pager_color_progress {color8.strip}
set -gx fish_pager_color_secondary_background {background.strip}
set -gx fish_pager_color_secondary_completion {foreground.strip}
set -gx fish_pager_color_secondary_description {color8.strip}
set -gx fish_pager_color_secondary_prefix {color10.strip}
set -gx fish_pager_color_selected_background --background={color8.strip}
set -gx fish_pager_color_selected_completion {foreground.strip}
set -gx fish_pager_color_selected_description {color8.strip}
set -gx fish_pager_color_selected_prefix {color10.strip}
