# Generated by hellwal

set -l wallpaper '%%wallpaper%%'

set -l background '%%background%%'
set -l foreground '%%foreground%%'
set -l cursor '%%cursor%%'
set -l border '%%border%%'

set -l color0 '%%color0.hex%%'
set -l color1 '%%color1.hex%%'
set -l color2 '%%color2.hex%%'
set -l color3 '%%color3.hex%%'
set -l color4 '%%color4.hex%%'
set -l color5 '%%color5.hex%%'
set -l color6 '%%color6.hex%%'
set -l color7 '%%color7.hex%%'
set -l color8 '%%color8.hex%%'
set -l color9 '%%color9.hex%%'
set -l color10 '%%color10.hex%%'
set -l color11 '%%color11.hex%%'
set -l color12 '%%color12.hex%%'
set -l color13 '%%color13.hex%%'
set -l color14 '%%color14.hex%%'
set -l color15 '%%color15.hex%%'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
