[options]
focus_follows_mouse = true
mouse_follows_focus = true
auto_center = false
preset_column_widths = [0.33333, 0.5, 0.66667]
animation_speed = 100

[padding]
top = 0
bottom = 0
left = 0
right = 0

[decorations.active.border]
enabled = true
color = "#f0f0f0"
opacity = 1.0
width = 4.0
radius = 8.0

[bindings]
window_focus_west = ["alt - leftarrow", "alt - h"]
window_focus_south = ["alt - downarrow", "alt - j"]
window_focus_north = ["alt - uparrow", "alt - k"]
window_focus_east = ["alt - rightarrow", "alt - l"]

window_swap_west = ["alt + shift - leftarrow", "alt + shift - h"]
window_swap_south = ["alt + shift - downarrow", "alt + shift - j"]
window_swap_north = ["alt + shift - uparrow", "alt + shift - k"]
window_swap_east = ["alt + shift - rightarrow", "alt + shift - l"]

window_swap_first = "alt + ctrl + shift - l"
window_swap_last = "alt + ctrl + shift - h"

window_stack = "alt - ,"
window_unstack = "alt + shift - ,"

window_center = "alt - ."
window_snap = "alt + shift - ."

window_resize = "alt - r"
window_fullwidth = "alt - m"
window_manage = "alt - f"

window_virtual_north = ["cmd + shift - k", "cmd + shift - uparrow"]
window_virtual_south = ["cmd + shift - j", "cmd + shift - downarrow"]
window_virtualmove_north = ["cmd + alt - k", "cmd + alt - uparrow"]
window_virtualmove_south = ["cmd + alt - j", "cmd + alt - downarrow"]

[windows.pip]
title = "^Picture-in-Picture$"
bundle_id = "org.mozilla.firefox"
floating = true

[windows.all]
title = ".*"
horizontal_padding = 0
vertical_padding = 0
width = 0.5
